language: node_js

node_js:
  - '5'

env:
  global:
    - NODE_ENV=CI
    - secure: OgqrxGlA46yY5sfm4r9UyGyiviHt6JoCaVU+lYKZUc+B6DE62Y7/alYLNxfIwqos875Rc57aEVd8ucNOuOgCch5IVKtUznXkpmwsIlu/5xXcmC/JR9ms6FPqADsiu/I75wxxEKVjxp6y/mW/Pq6+Xkg21t6/U0XG8EePIh+NZuSIFTM3Cey40aBUU6racdD6gWwe1cWu7Hk+rcsbvWoocLrGP434GBbek0gy+MHf9WldxnQi5A3axzqKxp2ICOoFF9YstNv/8TimbfC6S1DrmQWCbNN/9XzxtXkbxc8SncpGW0PYlL5/yzuTMqdSyBDk+oHjLKaYm1c+VKB38plwfskrxbSREq4+nH8LTIwDc0ZPsubWjiFxkbxiyTCc1w/XyVp2EYY21wXaEH7Ad3GW6HJBP2+zgSuSi7P35mETnZhKukk3x9G4qm1WYGU1bVZ4obbP2YpBf09+T/Ap46M9Jcu+pmb9/wWQ+55fjNDlVbDOK4EiPUBWMJO9O2dzljFW4qtfx5BvydNRxSIPDYvDDVCNKAPBiHHI/oSMQ+6YCy9T6wzC4MdOfD7X2O/51dQVd1kW7Us9JyD1NGEmSod/kF9qPEqgxiK6Ya25ajNVGE8w2FtU0EXcS1RprQvK06JaLgNMrN0JF86P3sEBO6yaUxqsT5v9egxG4XW8fIRzt9Y=
    - secure: TCF84wv8eUD0oStFf1ocal8BqJ0eQxB6pf+eF5I25zv6DFibS89tG/MNaGUMVHNcCH2Z3w2O7JfFNt97IJ0jr6WSzIRFFucKq6jVAhJnFUrdbV3PqATykFO7HyVoCAsV+QAA7Vw47SbUWGJ93bynyq24N2MC+LD4BZLt1HZgXADq9z74kY/82Za9JhV5wrucOY6SGpHIRKJN5jWzZj6Akq0fRRg8Lrjr3lE5jm8HIgflU6yRT2EMTj0q/SLU9MJ4ZLNDaDwyKkHULBK9WARbuZJCTG5kN+9BEfu+UcjWEq7/RLb9dujRWjEFme6ZzjaTHh+g3Am5VNuIxhQZl35BF7+E0uCBCXl9zs+tdGj1ygdmuL1B98Zv65VDEwstASbzJZADJYP4WSNcZbxSwMMsuMNyhQxSIYWUMgM1XuoaLuY7x5UqiZgmbf71cdE/y1SqYIWADWkaEZNfb8s5jaTaji9YGCVAHWoIB2mwTGiHH7w7R3Z+JJ/+nwLkM1KXYyL0HtXMXX+/U8yeIYl3/WyX5YudQJJ1AjXv/e860gNm2GQpq4KoFF4HZOrhqqXT7oXr6hD+bSDn3dyadTvvMLAfUHcYuW6JPj/T1heTsfBIo5zOjdCErvm5k9HQaVlJ1RgpaxvhZPGPQz3iMRHK++hvTa1tS5m9bvW5yPabXHDtLAQ=

cache:
  directories:
    - node_modules

git:
  depth: 100

before_install:
  - env | sort

script:
  - make check
  - make lint
  - make test
  - NODE_ENV=production make package

before_deploy: "echo 'Here we go!'"

deploy:
  provider: s3
  bucket: tldr.ostera.io
  on:
    node: '5'
    repo: ostera/tldr.jsx
    branch: ci-release
  skip_cleanup: true
  local-dir: dist
  acl: public_read
  secret_access_key: $AWS_SECRET_KEY
  access_key_id: $AWS_ACCESS_KEY

after_deploy:
  - ./scripts/invalidate-cdn-cache.sh $AWS_ACCESS_KEY $AWS_SECRET_KEY
