language: node_js

node_js:
  - '5'

env:
  global:
    - NODE_ENV=CI
    - secure: "hLDsLQKHuMU8mSEeRtuB2Tg+8l/bj1h+vPlcvbbzt94IH7zJii4cIm3bHu2ZeXJWFEGiwYLYXfokOkxS01sWwMH8QOisyd1WYAxiAe5YXdEn+JK3SMhBgZSNBJozPeL4gkAkP6FFshw85AZmZuaLZZTe3HuY+9tGnI6vxNGk5DILqU/hhkcuLQbXp/qDZxS/xK8hjH4YHw9H+AeYNBxbhF2nxlxWLhkXffnGZ5AUPiX3W060J0l8no6w5TeAtX+oDyPjhl4R95BRBsfIkzNO/IJk5qeL+WxmQjX2dd9Sl3oIgjXA2WeviSrKvb38ieakfrpKsduJIYMj75OpCdWjiZj5tW34OMiqQzwm/hElh1XCuuBaHZteGwQv026X88txH21UyJ9q+E8GrJKk92GZm73S4vYaoR74ePPnFea2YBwtIoo2r/T2pGsG4OOrc9DWaNDoKjF3YiiXt2hj9Py9W+Atg8cTzLF/gNOoxQPvYUZqftnEP6o0igxDDCOqWqmGpWNW2h07iJwj9PM6OY5GXo9naQVyE9uUy5wE1/mGZxTt0xx9FACkxzTZHgbe5mhrKlCsN28UeZY4881CTjh8wnKNEqKhIj3v7xOycC9y3VbJ7YLJoV5Q7Yy3AQ5dTKRu9eyKjVN+wucE3zeFqNMP6D8fW4rwDnNGn/1l4="
    - secure: "dS1Doj5BEEyGOXQ4UqqYP7/2Qm6YIQio1UxF+UQPLeVnHSa8QoiY26yGSQNh10rEtqmOz81/FeltHJgTeGF9GzfQvZ0dt9kj50Q/FmP/yVdE7DP8GvkSAEIOGDqC9nhldqbxV1hNIZRbYWA+jH40QbK/9Oqpo9e4fjYvoAjqrFfsc8fyszKzYYYI7KA+qWxtXAH0Y82BpEtlsYQtHUbmqmf4YKfEEKXIVQ8e4uiUuyDtNSpHKjECD2Vsw8URM8CNzk9UomiVAPg4NBIUGRyt5Ummd2X1ySt3Li4IqntpYZGiOcy33Dr5Ra9DpQN79IdLHelkA4tN10qumUkWj4HdVlBPK+gk6cQ7yv8RuMGuQqV356r1nt1He2eXhOa9mM5BlUo78lgOZj2eEjR1y1a3D9pZZUGsCZYuA58vbeK52KNo8X0lQwceTOWp4kgl6zNr9Yhtn0BTu/Ndt7FARnJeV6aeCjg23ilcUJsHHO5e0oRQgbABQWJzuAr2/wYnFi7Uf1FJLCltvVQJVwQ49YgrM0F2Tmp1gbvQ3e8JbBn7D8XE1h31LNqcZRWrwduR99bLBTy0IBElUdJgaWwzMaEWwjUI7oI6QF256Rv62bg588RZg3LfxVHWLoRMN7rkz5gWNC4f92g/Vf1JGk+M1ld2l+uealCnC/EUUUYEcXNUPpc="
    - AWS_CLOUDFRONT_DISTRIBUTION=E3019ANYLETHQX
    - MIXPANEL_TOKEN=4a7ada6639a7e0a8403a19527e40251d

cache:
  directories:
    - node_modules

git:
  depth: 100

before_install:
  - ./scripts/install-awscli.sh

script:
  - make setup
  - make check
  - make lint
  - make test
  - NODE_ENV=production make package

before_deploy: "echo 'Here we go!'"

deploy:
  provider: s3
  bucket: tldr.ostera.io
  on:
    node: '5'
    repo: ostera/tldr.jsx
  skip_cleanup: true
  local-dir: dist
  acl: public_read
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  access_key_id: $AWS_ACCESS_KEY_ID

after_deploy:
  - ./scripts/invalidate-cdn-cache.sh
