language: node_js

node_js:
  - '5'

env:
  global:
    - NODE_ENV=CI
    - AWS_CLOUDFRONT_DISTRIBUTION=E3019ANYLETHQX
    - MIXPANEL_TOKEN=4a7ada6639a7e0a8403a19527e40251d
    - secure: "Phe4fwVpTKPKgT3OxFUHofvB2/H/TiurHgZoNzNTO4Wq3V9yBmtsG5l52HQuws/jJhYaP3YD8pw50YFD3vqoWN57A1N483mSlTnb3J0j0zEKkHAq6gvaCZcs0pP/m5GrVyX+j+b7DCVv4rMcYZX7p1pH4Amo3pLpgx/LFhg7GY11ZLI2GRzySzXlJbYJIMUlDZKLxxdVp6fx92ElOeZFP9vGBqXdUGVw0ep5xtj2Vto73kE4KXYrXrq+jjueyoVaH3vik3YGrtHLZEag0UqqU+4utlRjy1Ar+IIeHvcEKdAjeQwNbXNkyhDFXcpPzqxR38xoiEKA0JHSvz3akvJCPjhQjdGN2UhnGLQzjGmubeoX7XjIPG0OOks5iiiG2tSASK5J7XMnXuTXbh4OSqH9MQds0Ga39N/OYASYCJQeNQ7/7vK2cHO/6ZT+8xv9O5ULZEWzeDHVtvzBcRpAE+A3FvQfsl+OVO2LAHeq78p0LimKocWaFSXcKQGiGI9+c0M7zBIMCVu2X6WMpDzL+Ug7zy7ZvrA6txqvPsbzwF81a8nOWoH3n4huo3Ll5MwbxSlyfRSLd8LN0nNRyyBe7APYGs64HL+u6/MvjcclHjVd8GVg5s/ATcQz0witGJ5hpUnkPVV50TmqJgoNAoIbeDYyQ8tem0ikFxazcHBqbsqMFPE="
    - secure: "G10XouTBBYn6uQDlckig/rQxdPzDfLTaeS+LgA+Q1rmyOO9Xy7Xi/H7y9VWk6+rt+vx23DiTgYQhMm2449BZbxxPTsYJPmAt6x0NzesZaIyW6znxUh3wdWXsZFVO+IS2l2pPyYGKI0IDMWNbnm/Fkp/EQ/zPlN9OyRX+HH9I4BOIGsNZOwO4JzWYYNfHKrTth2TX60dwQMUqTmDAb6WVmdvZkAlbqhe/naU585/MN7y459qwi7ler978lmm4L+p9l4ngNlRFLeU9fbKOx2yK4XUOeOLSjJ2Mzh2TfKV0hZ7AqmIWJ8hjdQNhjnrSb9XbkdTz5fouxgmQeqlQBlc6VTn2dOI35leu3MMZfymEb7uk/Cazk7n0QpW/lKsVD+nsSfQ/TkU1jEyBnSrY7OUN/cJa/XHEoUCkh+IkKapB0NgmjK0qBLoMiz3qmnuqtbR+tkWUAzsWlrr9Xz1TwKIkMBWH6AnCYPV886KccGd1vRJ446JbpXIuUIeL4Lmiqo2zWSQ1wMkvGYGvsiUm+APhmdV3gHN914sv9OGwN3m84DjnKfv7xCSoG6WrdhvjjY/y58dh7o07c1wBDP7afS51scHKTig3v1HZ5f5Ne8t0ZFskjXYJC+Dn13kzozqqw1YreOkX58OM1UmoS9S7UnmWF1LzJqxqi86yuwhcl1cnyZ0="

cache:
  directories:
    - node_modules
    - .bin/aws

git:
  depth: 100

before_install:
  - ./scripts/install-awscli.sh

script:
  - make setup
  - make check
  - make lint
  - make test
  - NODE_ENV=production make package

before_deploy: "echo 'Here we go!'"

deploy:
  provider: s3
  bucket: tldr.ostera.io
  on:
    node: '5'
    repo: ostera/tldr.jsx
  skip_cleanup: true
  local-dir: dist
  acl: public_read
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  access_key_id: $AWS_ACCESS_KEY_ID

after_deploy:
  - ./scripts/invalidate-cdn-cache.sh
