language: node_js

node_js:
  - '5'

env:
  global:
    - NODE_ENV=CI
    - AWS_CLOUDFRONT_DISTRIBUTION=E3019ANYLETHQX
    - MIXPANEL_TOKEN=4a7ada6639a7e0a8403a19527e40251d
    - secure: "JH9dHemNeMlZEJtD9OUsZWRYfaCtslySCcrkmcN5hrE+KYbxTE7euLsyrrcGyB5frWBWldEAIcqR48Y7H+T5HqIIFoM194/hQKJCJuXaAQSbdMA2KAFd5whSV/TOyc6G81nJLgOmUwy3RblDT2WzQ+5A9Cd94FHI6vWPmdpD5zCGrZymEgn+w+14uXiKnjSvhaM25B09X5AXudFGZYYYIoc2+9wxzHSs2uSGhN3u2EWBkJG/fE3NKK7fym7u1nxwkOnYPzTzp2IM5UDJZzQOVpgBYyByAGiFbWzDXNusuBXjgtDAM9IwzDxJUAJ690ApnTO8e8gaI2dkgch9RSbq59m5C/BqxNM5ML8e+vPSfp2WvJWPgifr318sWEUNhJ4koMdn89IEdH701DakqTqoVkUIr42ts3AMePeEdQB+MbjULHg1g6CtjTzwSdI0CDVjyEuzY627O6xqEvRbd2EU9gFMwctMw7BASRwr3HqVA7YkI5701W0MqnrN1y9lano5krp9aiRTdnpkBbHcDuWC5d1WVY7I91etytKpskiS+oCVtx8cFC24HVh7KBzH/2ICVB5T3dvxE9Yy11W7tDoSDy5ZUbp0UWdz+P78WQjia9joHp3N3SZlel1NkkjsZfB3i8U8T4rq++1IYU7/135gRTXFOC9bXAvbUm6egfe/jPo="
    - secure: "Az8VHB2YvAfqgRSnzdSCKWdParuFtg51O+cLsXh7M+EjPXndH4J/O9yBJMe33gZXRDkqtQBuNYMknX41UgflWNno/kcH25/XeKWWX6TvvHbqOzHQ0phTasE8heK8hxInJcA8Xrj7enSw2aaIP0aztq8U60hT2diuHDxGM9vYnfrp0wEMzjsviUcMOuNI/X/XAADQJRH6MrQY1wjZi35c0N/RYrMCs5gg2rVWogAhoIjeWpCfd4QF8xJJ7YkHNiwq5fXuoib/ZjcvxxhgeGbSw7zHu2D5sLnROIMpubXqUXi9BvJWfTE870w7lMs/KFjnuuHK63dNuQzF8+n4sBGRh3nfaWrYpw9+sditRbprTCPR05aMKDqdaMZMEtO/Ie7n3KFEIZ9K8LJmjeN7cqFXT9n2wMYxbmlhkdbI+oX5rxsDyJb6EHCwSVyZZKDd6GkfSgdXrBbpQH2xZ2woZoWEonHF/J/J7SuRV+TnVvGbYU7Pjxcmbh7vs8wMcHC+iW3kD/xTjoA+o/9QNhQOB8JU7DFYoe2XV0Bt9CKqYCxQnxGsmis0RCzR+b+dFcW0un0oi/C4EXkIuCbSLvOMXwmUL9FkA68PClzwgwg5OUnyzqOmBGQr3HzXt8TDKoKRxLDxvXRFdrrIt26J5YROrF+ZMHTLims45ff3U5EsaPBYrLw="

cache:
  directories:
    - node_modules

git:
  depth: 100

before_install:
  - ./scripts/install-awscli.sh

script:
  - make setup
  - make check
  - make lint
  - make test
  - NODE_ENV=production make package

before_deploy: "echo 'Here we go!'"

deploy:
  provider: s3
  bucket: tldr.ostera.io
  on:
    node: '5'
    repo: ostera/tldr.jsx
  skip_cleanup: true
  local-dir: dist
  acl: public_read
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  access_key_id: $AWS_ACCESS_KEY_ID

after_deploy:
  - ./scripts/invalidate-cdn-cache.sh
